#!/bin/bash
echo "=== ПРОВЕРКА ИНДЕКСАЦИИ FATTORIA.BY ==="
echo ""
echo "1. GOOGLE:"
echo "   • Ручная проверка: https://www.google.com/search?q=site:fattoria.by"
echo "   • Search Console: https://search.google.com/search-console"
echo ""
echo "2. YANDEX:"
echo "   • Ручная проверка: https://yandex.ru/search/?text=site:fattoria.by"
echo "   • Вебмастер: https://webmaster.yandex.ru"
echo ""
echo "3. ТЕКУЩИЙ СТАТУС САЙТА:"
curl -s -o /dev/null -w "• Доступность: %{http_code}\n• Время ответа: %{time_total}сек\n" "https://fattoria.by"
echo ""
echo "4. РЕКОМЕНДАЦИИ:"
echo "   ✓ Добавь сайт в Google Search Console"
echo "   ✓ Добавь в Яндекс.Вебмастер"
echo "   ✓ Создай и добавь sitemap.xml"
echo "   ✓ Настрой analytics"
echo ""
echo "✅ Проверка завершена!"
